# Generated by Django 5.1.5 on 2025-01-23 10:42

import admin_panel.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(validators=[admin_panel.models.validate_dob])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
                ('customer_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('aadhar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be exactly 12 digits.')])),
                ('pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}\\d{4}[A-Z]{1}$', 'PAN must be in the correct format (e.g., ABCDE1234F).')])),
                ('aadhar_document', models.FileField(upload_to='kyc_documents/aadhar/')),
                ('pan_document', models.FileField(upload_to='kyc_documents/pan/')),
                ('communication_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Account number must contain only digits.')])),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC code format.')])),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('corporate', 'Corporate')], max_length=10)),
                ('kyc_status', models.BooleanField(default=False)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('customer', models.OneToOneField(help_text='Each customer can only have one account.', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='admin_panel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_deposits', to='admin_panel.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='InterBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_method', models.CharField(choices=[('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('UPI', 'UPI')], max_length=10)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='admin_panel.customeraccount')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='admin_panel.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('general', 'General')], default='general', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admin_panel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OtherBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_account_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Account number must contain only digits.')])),
                ('receiver_ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC code format.')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_method', models.CharField(choices=[('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('UPI', 'UPI')], max_length=10)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='admin_panel.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='admin_panel.customeraccount')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='admin_panel.customeraccount')),
            ],
        ),
    ]
