# Generated by Django 5.1.5 on 2025-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='name',
            field=models.TextField(default=0.0009053497942386831),
            preserve_default=False,
        ),
    ]
