# Generated by Django 5.1.5 on 2025-01-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_cashdeposit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdeposit',
            name='name',
        ),
    ]
